server:
  # ??????
  port: 8083
  servlet:
    # ???????
    context-path: /music-share

spring:
  application:
    # ????
    name: music-share
  profiles:
    # ????
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
    max-file-size: 10MB # 单个上传⽂件⼤⼩限定为10M
    max-request-size: 100MB # 单次上传⽂件⼤⼩限定为100M

# ?????????
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  # ????????????
  type-aliases-package: com.hahaha.*.entity
  configuration:
    # ???????
    map-underscore-to-camel-case: true
    cache-enabled: false
    # ????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ??????
      logic-delete-field: true
      logic-delete-value: 1
      logic-not-delete-value: 0

# ????????
logging:
  # ??????
  config: target/classes/log/ logback-spring.xml

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      # ?? controller ?????????
      packages-to-scan: com.hahaha.musicshare.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

# ??????????? url ????????
auth:
  valid_urls:
    - /auth/logout
    - /user/**
    - /resource/publish

# ??? OSS ????????
aliyun:
  oss:
    # oss ?????????
    endpoint: oss-cn-nanjing.aliyuncs.com
    # ?????????????
    accessKeyId: LTAI5tQ264G7BjAej4z1Ht2A

    # ???????????? oss ????????????
    accessKeySecret: nbhMbEIpBBmC9vzUTZWUQRAbiiOdu5

    # oss??????
    bucketName: xiaohexiansheng

# ??????????????
share:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c93863e4f01938abc945a00e2
      accountToken: baf4abfb77874086aa54edb0cdc6986f
      appId: 2c94811c93863e4f01938abc960e00e9
      templateId: 1